version: '3.7'

services:
  nginx:
    container_name: "gateway"
    build: nginx
    ports:
      - "12345:12345"
    networks:
      - app-network

  webapp:
    container_name: "webapp"
    build: ../
    ports:
      - "3010:3000"
    networks:
      - app-network

volumes:
  app:

networks:
  app-network:
    driver: bridge